[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
